In [0]:
import numpy as np
a = np.array([[22,13,5,27],[5,20,19,0],[16,19,1,15],[9,0,16,19]])
b = np.array([[10,5,26,27],[5,21,19,8],[20,22,22,18],[20,27,3,7]])


In [5]:
#1
a+b


array([[32, 18, 31, 54],
       [10, 41, 38,  8],
       [36, 41, 23, 33],
       [29, 27, 19, 26]])

In [6]:
#2
a-b

array([[ 12,   8, -21,   0],
       [  0,  -1,   0,  -8],
       [ -4,  -3, -21,  -3],
       [-11, -27,  13,  12]])

In [7]:
#3
a*b

array([[220,  65, 130, 729],
       [ 25, 420, 361,   0],
       [320, 418,  22, 270],
       [180,   0,  48, 133]])

In [0]:
#4
c = np.dot(a,b)

In [10]:
c

array([[ 925, 1222, 1010,  977],
       [ 530,  863,  928,  637],
       [ 575,  906,  844,  707],
       [ 790,  910,  643,  664]])

In [0]:
c = np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
d = np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

In [21]:
#5
c+d

array([27, 18, 41, 29, 30, 26, 25, 31, 30, 21, 23, 12, 25, 50, 28, 26])

In [22]:
#6
c-d

array([ 21, -12,  -7, -15,  -8, -22,  17, -27,  18,  15, -17,  10,   3,
         0, -24,  14])

array([ 72,  45, 408, 154, 209,  48,  84,  58, 144,  54,  60,  11, 154,
       625,  52, 120])

In [0]:
#8
e = np.dot(c, d)

In [25]:
e

2298

In [27]:
#9
a + 10

array([[32, 23, 15, 37],
       [15, 30, 29, 10],
       [26, 29, 11, 25],
       [19, 10, 26, 29]])

In [28]:
#10
b + 10

array([[20, 15, 36, 37],
       [15, 31, 29, 18],
       [30, 32, 32, 28],
       [30, 37, 13, 17]])

In [29]:
#11
c + 15

array([39, 18, 32, 22, 26, 17, 36, 17, 39, 33, 18, 26, 29, 40, 17, 35])

In [30]:
#12
d + 15

array([18, 30, 39, 37, 34, 39, 19, 44, 21, 18, 35, 16, 26, 40, 41, 21])

In [32]:
#13
(2*a)+(2*b)

array([[ 64,  36,  62, 108],
       [ 20,  82,  76,  16],
       [ 72,  82,  46,  66],
       [ 58,  54,  38,  52]])

In [33]:
#14
(a+b)*3

array([[ 96,  54,  93, 162],
       [ 30, 123, 114,  24],
       [108, 123,  69,  99],
       [ 87,  81,  57,  78]])

In [34]:
#15
(a-b+a-b+b)*4

array([[ 136,   84,  -64,  108],
       [  20,   76,   76,  -32],
       [  48,   64,  -80,   48],
       [  -8, -108,  116,  124]])