In [2]:
import numpy as np

x = np.array([1,2,3])
y = np.array([1,2,3])
a = np.zeros((2,2))
b = np.ones((2,2))
print(a+b)
print(a/b)
c = np.random.randint(10, size =(5))
d = np.random.randint(10, size =(5))
print(c+d)
print(c*d)
e = np.random.random((2,2))
print(e)

f = np.array([1,2,3])
g = np.array([4,5,6])
h = np.add(f, g)
print(h)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[ 9  8 13  9 13]
[ 8  7 40 14 42]
[[0.15971746 0.82191227]
 [0.74979454 0.65846715]]
[5 7 9]


In [3]:
for number in x:
  print(number, end=',')
print(np.equal(x,y))
j = np.argmax(x)
print(j)
sqroot = np.sqrt(x)
print(sqroot)

1,2,3,[ True  True  True]
2
[1.         1.41421356 1.73205081]


In [4]:
aa = np.array([[1,2],[3,4]])
print (np.sum(aa))
print (np.sum(aa, axis=0))#each column
print (np.sum(aa, axis=1))#each row


10
[4 6]
[3 7]
